name: cicd

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  USERNAME: artempronevskiy
  USEREMAIL:  artem.pronevskiy@gmail.com 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x,]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run build
    - run: |
        git remote set-url --push origin https://$USERNAME:$GITHUB_TOKEN@github.com/pymentor/pymentor-landing-page
        git config --local user.email "$USEREMAIL"
        git config --local user.name "$USERNAME"
        git commit -am "update info"
        git push
